name: maroofkhan8
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4


#==========================================#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  smooth_page_indicator:
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  device_preview:
  flutter_easyloading:
  pin_code_fields: ^8.0.1
  image_picker: ^1.2.1
  mime: ^2.0.0
  url_launcher: ^6.2.5



#===========================================#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0




#==========================================#
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
